const express = require("express");
const Link = require("../models/Link");
const authMiddleware = require("../middleware/auth");
const { autoTag } = require("../utils/autoTagger");

const router = express.Router();

router.use(authMiddleware);

// GET /api/links/community — all public links (even from others)
router.get("/community", async (req, res) => {
  try {
    const { search, tag } = req.query;
    const query = { isPublic: true };

    if (tag) query.tags = { $in: [tag.toLowerCase()] };
    if (search) {
      query.$or = [
        { title: { $regex: search, $options: "i" } },
        { description: { $regex: search, $options: "i" } },
        { url: { $regex: search, $options: "i" } },
      ];
    }

    const links = await Link.find(query).populate("userId", "username email").sort({ createdAt: -1 });
    res.status(200).json({ success: true, count: links.length, links });
  } catch (error) {
    console.error("Get community links error:", error);
    res.status(500).json({ success: false, message: "Server error fetching community links." });
  }
});

// POST /api/links/bulk — create multiple links at once
router.post("/bulk", async (req, res) => {
  try {
    const { links } = req.body; // Array of { url, title, description, tags, isPublic }

    if (!Array.isArray(links) || links.length === 0) {
      return res.status(400).json({ success: false, message: "An array of links is required." });
    }

    const createdLinks = [];
    for (const item of links) {
      const { url, title, description, tags, isPublic } = item;
      if (!url) continue;

      // Simple title fallback from URL if title is missing
      let finalTitle = title;
      if (!finalTitle) {
        try {
          const domain = new URL(url).hostname.replace("www.", "");
          finalTitle = domain.charAt(0).toUpperCase() + domain.slice(1);
        } catch {
          finalTitle = "New Resource";
        }
      }

      const autoGeneratedTags = autoTag(finalTitle, description || "");
      const finalTags =
        tags && tags.length > 0
          ? [...new Set([...tags.map((t) => t.toLowerCase()), ...autoGeneratedTags])]
          : autoGeneratedTags;

      const link = await Link.create({
        userId: req.user.userId,
        url,
        title: finalTitle,
        description: description || "",
        tags: finalTags,
        isPublic: isPublic !== undefined ? isPublic : true,
      });
      createdLinks.push(link);
    }

    res.status(201).json({
      success: true,
      message: `Successfully created ${createdLinks.length} links.`,
      links: createdLinks,
    });
  } catch (error) {
    console.error("Bulk create links error:", error);
    res.status(500).json({ success: false, message: "Server error during bulk link creation." });
  }
});

// GET /api/links/tags — must be BEFORE /:id routes
router.get("/tags", async (req, res) => {
  try {
    const tags = await Link.distinct("tags", { userId: req.user.userId });
    res.status(200).json({ success: true, tags: tags.sort() });
  } catch (error) {
    console.error("Get tags error:", error);
    res.status(500).json({ success: false, message: "Server error fetching tags." });
  }
});

// POST /api/links/autotag — preview auto-tags before saving
router.post("/autotag", async (req, res) => {
  try {
    const { title, description } = req.body;
    if (!title) {
      return res.status(400).json({ success: false, message: "Title is required for auto-tagging." });
    }
    const suggestedTags = autoTag(title, description);
    res.status(200).json({ success: true, suggestedTags });
  } catch (error) {
    console.error("Auto-tag error:", error);
    res.status(500).json({ success: false, message: "Server error during auto-tagging." });
  }
});

// GET /api/links
router.get("/", async (req, res) => {
  try {
    const { search, tag, favorite } = req.query;
    const query = { userId: req.user.userId };

    if (tag) query.tags = { $in: [tag.toLowerCase()] };
    if (favorite === "true") query.isFavorite = true;
    if (search) {
      query.$or = [
        { title: { $regex: search, $options: "i" } },
        { description: { $regex: search, $options: "i" } },
        { url: { $regex: search, $options: "i" } },
      ];
    }

    const links = await Link.find(query).sort({ createdAt: -1 });
    res.status(200).json({ success: true, count: links.length, links });
  } catch (error) {
    console.error("Get links error:", error);
    res.status(500).json({ success: false, message: "Server error fetching links." });
  }
});

// POST /api/links — create a new link (as current user)
router.post("/", async (req, res) => {
  try {
    const { url, title, description, tags, isPublic } = req.body;

    if (!url || !title) {
      return res.status(400).json({ success: false, message: "URL and title are required." });
    }

    const autoGeneratedTags = autoTag(title, description);
    const finalTags =
      tags && tags.length > 0
        ? [...new Set([...tags.map((t) => t.toLowerCase()), ...autoGeneratedTags])]
        : autoGeneratedTags;

    const link = await Link.create({
      userId: req.user.userId,
      url,
      title,
      description: description || "",
      tags: finalTags,
      isPublic: isPublic !== undefined ? isPublic : true,
    });

    res.status(201).json({ success: true, message: "Link saved successfully.", link });
  } catch (error) {
    console.error("Create link error:", error);
    res.status(500).json({ success: false, message: "Server error creating link." });
  }
});

// PUT /api/links/:id
router.put("/:id", async (req, res) => {
  try {
    const { url, title, description, tags, isFavorite } = req.body;

    const link = await Link.findOne({ _id: req.params.id, userId: req.user.userId });

    if (!link) {
      return res.status(404).json({
        success: false,
        message: "Link not found or you do not have permission to edit it.",
      });
    }

    if (url) link.url = url;
    if (title) link.title = title;
    if (description !== undefined) link.description = description;
    if (typeof isFavorite === "boolean") link.isFavorite = isFavorite;

    if (title || description) {
      const autoGeneratedTags = autoTag(link.title, link.description);
      link.tags =
        tags && tags.length > 0
          ? [...new Set([...tags.map((t) => t.toLowerCase()), ...autoGeneratedTags])]
          : autoGeneratedTags;
    } else if (tags) {
      link.tags = [...new Set(tags.map((t) => t.toLowerCase()))];
    }

    await link.save();
    res.status(200).json({ success: true, message: "Link updated successfully.", link });
  } catch (error) {
    console.error("Update link error:", error);
    res.status(500).json({ success: false, message: "Server error updating link." });
  }
});

// DELETE /api/links/:id
router.delete("/:id", async (req, res) => {
  try {
    const link = await Link.findOneAndDelete({ _id: req.params.id, userId: req.user.userId });

    if (!link) {
      return res.status(404).json({
        success: false,
        message: "Link not found or you do not have permission to delete it.",
      });
    }

    res.status(200).json({ success: true, message: "Link deleted successfully." });
  } catch (error) {
    console.error("Delete link error:", error);
    res.status(500).json({ success: false, message: "Server error deleting link." });
  }
});

module.exports = router;
